[pytest]

addopts=-vs --alluredir=./temps --clean-alluredir
testpaths=./testcase
python_files=test_*.py
python_classes=Test*
python_functions=test_*

markers=
    smoke: 冒烟测试
    regression: 回归测试

[base_url]
base_url=http://your-api-server:8082
